variable "ldap_url" {}
variable "bind_dn" {}
variable "bind_pass" {}
variable "user_dn" {}
variable "group_dn" {}
variable "user_addr" {}
variable "group_filter" {}
variable "group_attr" {}
#variable "user_filter" {}